[package]
name = "roperator"
version = "0.1.0"
authors = ["pfried <philipsfried@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = { version = "=0.13.0-alpha.4", features = ["unstable-stream"]}
http = "^0.1.15"
tokio = "0.2.0-alpha.6"
tokio-executor = "0.2.0-alpha.6"
bytes = "0.4.12"
hyper-openssl = "=0.8.0-alpha.4"
futures-util-preview = "=0.3.0-alpha.19"
openssl = "^0.10.19"
serde_json = "1.0.41"
serde = "1.0.101"
serde_derive = "1.0.101"
failure = "0.1.6"
log = "0.4.8"
env_logger = "0.7.1"
regex = "*"
lazy_static = "*"
url = "2.1.0"
# The latest version of the "futures" library, which has lots of utilities
# for writing async code. Enable the "compat" feature to include the
# functions for using futures 0.3 and async/await with the Hyper library,
# which use futures 0.1.
futures-preview = { version = "=0.3.0-alpha.19", features = ["compat"] }
urlencoding = "1.0.0"
kube = { version = "0.17.0", features = ["openapi"] }

[dev-dependencies]
serde_derive = "1.0.101"
k8s-openapi = { version = "0.6.0", default-features = false, features = ["v1_15"] }
env_logger = "*"

