# This is the CustomResourceDefinition for our EchoServer application.
# You must create this CRD in your k8s cluster prior to running the example.
# To do so, run: `kubectl create -f examples/echo-server/crd.yaml`
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: echoservers.example.roperator.com
spec:
  group: example.roperator.com
  versions:
    - name: v1alpha1
      storage: true
      served: true
  scope: Namespaced
  subresources:
    status: {}
  names:
    kind: EchoServer
    plural: echoservers
    singular: echoserver
    shortNames:
    - echo
