apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: echoservers.example.roperator.com
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: example.roperator.com
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1alpha1
      storage: true
      served: true
  scope: Namespaced
  subresources:
    status: {}
  names:
    kind: EchoServer
    plural: echoservers
    singular: echoserver
    shortNames:
    - echo
