apiVersion: v1
kind: Config
current-context: ca-path-context
clusters:
- name: with-ca-path
  cluster:
    server: https://with-ca-path.test
    certificate-authority: ./dummy-ca.crt
contexts:
- context:
    cluster: with-ca-path
    user: certificates
  name: ca-path-context
- context:
    cluster: with-ca-path
    user: certificates
  name: ca-data-context
preferences: {}
users:
- name: certificates
  user:
    client-certificate-data: ABC
    client-key-data: '123'
